services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - srv-pedido-network
    volumes:
      - rabbitmq-data:/data/rabbit-mq

  srv-pedido-receiver:
    container_name: srv-pedido-receiver
    image: fmmelo/srv-pedido-receiver:1.0.0
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - srv-pedido-network
    volumes:
      - srv-pedido-receiver-data:/data/pedido-receiver
    environment:
      - RABBITMQ_USERNAME=myuser
      - RABBITMQ_PASS=secret
    ports:
      - "8080:8080"
    restart: always

  srv-pedido-consumer:
    container_name: srv-pedido-consumer
    image: fmmelo/srv-pedido-consumer:1.0.1
    links:
      - rabbitmq
      - mongodb-pedido-consumer
    depends_on:
      - rabbitmq
      - mongodb-pedido-consumer
    networks:
      - srv-pedido-network
    volumes:
      - srv-pedido-consumer-data:/data/pedido-consumer
    environment:
      - RABBITMQ_USERNAME=myuser
      - RABBITMQ_PASS=secret
      - MONGODB_USERNAME=root
      - MONGODB_PASS=rootpass
    ports:
      - "8081:8081"
    restart: always

  mongodb-pedido-consumer:
    image: mongo:latest  
    container_name: mongodb-pedido-consumer
    ports:
      - "27019:27017"  
    volumes:
      - mongodb-pedido-consumer-data:/data/db  
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root  
      - MONGO_INITDB_ROOT_PASSWORD=rootpass  
    networks:
      - srv-pedido-network

  srv-estoque:
    container_name: srv-estoque
    image: fmmelo/srv-estoque:1.0.0
    links:
      - mongodb-estoque
    depends_on:
      - mongodb-estoque
    networks:
      - srv-pedido-network
    volumes:
      - srv-estoque-data:/data/estoque
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASS=rootpass
    ports:
      - "8082:8082"
    restart: always

  mongodb-estoque:
    image: mongo:latest  
    container_name: mongodb-estoque
    ports:
      - "27020:27017"
    volumes:
      - mongodb-estoque-data:/data/db  
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root  
      - MONGO_INITDB_ROOT_PASSWORD=rootpass  
    networks:
      - srv-pedido-network

  srv-pagamento:
    container_name: srv-pagamento
    image: fmmelo/srv-pagamento:1.0.0
    links:
      - mongodb-pagamento
    depends_on:
      - mongodb-pagamento
    networks:
      - srv-pedido-network
    volumes:
      - srv-pagamento-data:/data/pagamentos
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASS=rootpass
    ports:
      - "8083:8083"
    restart: always

  mongodb-pagamento:
    image: mongo:latest  
    container_name: mongodb-pagamento
    ports:
      - "27021:27017"
    volumes:
      - mongodb-pagamento-data:/data/db  
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root  
      - MONGO_INITDB_ROOT_PASSWORD=rootpass  
    networks:
      - srv-pedido-network

  srv-cliente:
    container_name: srv-cliente
    image: harisantana/srv-cliente:1.0.0
    links:
      - db-cliente
    depends_on:
      - db-cliente
    networks:
      - srv-pedido-network
    volumes:
      - srv-cliente-data:/data/clientes
    environment:
      - MYSQL_URL=jdbc:mysql://db-cliente/clientesdb
      - MYSQL_DATABASE=clientesdb
      - MYSQL_USER=fiap
      - MYSQL_PASSWORD=fiap123
    ports:
      - "8085:8085"
    restart: always

  db-cliente:
    image: mysql:latest
    container_name: db-cliente
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=clientesdb
      - MYSQL_USERNAME=fiap
      - MYSQL_PASSWORD=fiap123
    volumes:
      - db-cliente-data:/var/lib/mysql
    networks:
      - srv-pedido-network

  srv-produto:
    container_name: srv-produto
    image: harisantana/srv-produto:1.0.0
    links:
      - db-produto
    depends_on:
      - db-produto
    networks:
      - srv-pedido-network
    volumes:
      - srv-produto-data:/data/produtos
    environment:
      - MYSQL_URL=jdbc:mysql://db-produto/produtosdb
      - MYSQL_DATABASE=produtosdb
      - MYSQL_USERNAME=admin
      - MYSQL_PASSWORD=adminpass
    ports:
      - "8086:8086"
    restart: always

  db-produto:
    image: mysql:latest
    container_name: db-produto
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=produtosdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=adminpass
    volumes:
      - db-produto-data:/var/lib/postgresql/data
    networks:
      - srv-pedido-network

networks:
  srv-pedido-network:

volumes:
  rabbitmq-data:
  srv-pedido-receiver-data:
  srv-pedido-consumer-data:
  mongodb-pedido-consumer-data:
  srv-pagamento-data:
  mongodb-pagamento-data:
  srv-estoque-data:
  mongodb-estoque-data:
  srv-cliente-data:
  db-cliente-data:
  srv-produto-data:
  db-produto-data:
